-- Platform Avrupa — 300 Kanonik Türk Ürünü
-- supabase_schema_v2.sql çalıştırıldıktan sonra çalıştır.
-- ON CONFLICT DO NOTHING: tekrar çalıştırmak güvenli.

INSERT INTO canonical_products (slug, name_tr, tip, nl_search, category, unit_type, is_ethnic) VALUES

-- ─── 1. Süt & Süt Ürünleri (25) ──────────────────────────────
('yari-yagli-sut',        'Yarım Yağlı Süt',         'sepet', 'halfvolle melk 1L',              'Süt & Süt Ürünleri', '€/L',    false),
('tam-yagli-sut',         'Tam Yağlı Süt',            'sepet', 'volle melk 1L',                  'Süt & Süt Ürünleri', '€/L',    false),
('yagsiz-sut',            'Yağsız Süt',               'sepet', 'magere melk 1L',                 'Süt & Süt Ürünleri', '€/L',    false),
('laktozsuz-sut',         'Laktozsuz Süt',             'sepet', 'lactosevrije melk 1L',           'Süt & Süt Ürünleri', '€/L',    false),
('uht-sut',               'UHT Uzun Ömürlü Süt',      'sepet', 'houdbare melk 1L',               'Süt & Süt Ürünleri', '€/L',    false),
('ayran',                 'Ayran',                    'sepet', 'karnemelk ayran 1L',             'Süt & Süt Ürünleri', '€/L',    false),
('sade-yogurt',           'Sade Yoğurt',               'sepet', 'natuuryoghurt 1kg',              'Süt & Süt Ürünleri', '€/kg',   false),
('yunan-yogurdu',         'Yunan Yoğurdu',             'sepet', 'Griekse yoghurt',               'Süt & Süt Ürünleri', '€/kg',   false),
('kefir',                 'Kefir',                    'sepet', 'kefir',                          'Süt & Süt Ürünleri', '€/L',    false),
('sivi-krema',            'Sıvı Krema',                'sepet', 'culinaire room',                 'Süt & Süt Ürünleri', '€/L',    false),
('suzme-labne',           'Süzme / Labne',             'sepet', 'kwark labne',                   'Süt & Süt Ürünleri', '€/kg',   false),
('beyaz-peynir-feta',     'Beyaz Peynir / Feta',      'sepet', 'feta 200g',                      'Süt & Süt Ürünleri', '€/kg',   false),
('hellim',                'Hellim',                   'sepet', 'halloumi',                       'Süt & Süt Ürünleri', '€/kg',   false),
('genc-kasar-gouda',      'Genç Kaşar (Gouda)',       'sepet', 'jonge kaas gouda',               'Süt & Süt Ürünleri', '€/kg',   false),
('eski-kasar',            'Eski Kaşar',               'sepet', 'belegen kaas',                   'Süt & Süt Ürünleri', '€/kg',   false),
('rendelenmis-peynir',    'Rendelenmiş Peynir',       'sepet', 'geraspte kaas',                  'Süt & Süt Ürünleri', '€/kg',   false),
('mozzarella',            'Mozzarella',               'sepet', 'mozzarella 125g',                'Süt & Süt Ürünleri', '€/kg',   false),
('krem-peynir',           'Krem Peynir',              'marka', 'smeerkaas Philadelphia',         'Süt & Süt Ürünleri', '€/kg',   false),
('ucgen-peynir',          'Üçgen Peynir',             'sepet', 'smeltkaas',                      'Süt & Süt Ürünleri', '€/kg',   false),
('tereyagi',              'Tereyağı',                 'sepet', 'boter 250g',                     'Süt & Süt Ürünleri', '€/kg',   false),
('margarin',              'Margarin',                 'sepet', 'margarine',                      'Süt & Süt Ürünleri', '€/kg',   false),
('yumurta-10lu',          'Yumurta 10''lu',           'sepet', 'eieren 10 stuks',                'Süt & Süt Ürünleri', '€/adet', false),
('yumurta-6li',           'Yumurta 6''lı',            'sepet', 'eieren 6 stuks',                 'Süt & Süt Ürünleri', '€/adet', false),
('cikolatali-sut',        'Çikolatalı Süt',           'marka', 'chocolademelk',                  'Süt & Süt Ürünleri', '€/L',    false),
('puding-muhallebi',      'Puding / Muhallebi',       'sepet', 'pudding',                        'Süt & Süt Ürünleri', '€/kg',   false),

-- ─── 2. Et, Tavuk & Balık (25) ───────────────────────────────
('tavuk-gogsu',           'Tavuk Göğsü',              'sepet', 'kipfilet 1kg',                   'Et, Tavuk & Balık',  '€/kg',   false),
('tavuk-but',             'Tavuk But',                'sepet', 'kippenbout dij',                 'Et, Tavuk & Balık',  '€/kg',   false),
('tavuk-kanat',           'Tavuk Kanat',              'sepet', 'kippenvleugels',                 'Et, Tavuk & Balık',  '€/kg',   false),
('butun-tavuk',           'Bütün Tavuk',              'sepet', 'hele kip',                       'Et, Tavuk & Balık',  '€/kg',   false),
('tavuk-kiyma',           'Tavuk Kıyma',              'sepet', 'kipgehakt',                      'Et, Tavuk & Balık',  '€/kg',   false),
('hindi-gogsu',           'Hindi Göğsü',              'sepet', 'kalkoenfilet',                   'Et, Tavuk & Balık',  '€/kg',   false),
('dana-kiyma',            'Dana Kıyma',               'sepet', 'rundsgehakt 1kg',                'Et, Tavuk & Balık',  '€/kg',   false),
('karisik-kiyma',         'Karışık Kıyma',            'sepet', 'gemengd gehakt',                 'Et, Tavuk & Balık',  '€/kg',   false),
('dana-kusbasi',          'Dana Kuşbaşı',             'sepet', 'rundsblokjes stoofvlees',        'Et, Tavuk & Balık',  '€/kg',   false),
('dana-biftek',           'Dana Biftek',              'sepet', 'biefstuk',                       'Et, Tavuk & Balık',  '€/kg',   false),
('dana-rosto',            'Dana Rosto',               'sepet', 'rosbief',                        'Et, Tavuk & Balık',  '€/kg',   false),
('kuzu-pirzola',          'Kuzu Pirzola',             'sepet', 'lamskotelet',                    'Et, Tavuk & Balık',  '€/kg',   false),
('kuzu-but',              'Kuzu But',                 'sepet', 'lamsbout',                       'Et, Tavuk & Balık',  '€/kg',   false),
('hazir-kofte',           'Hazır Köfte',              'sepet', 'gehaktballen',                   'Et, Tavuk & Balık',  '€/kg',   false),
('sucuk',                 'Sucuk',                    'marka', 'sucuk helal',                    'Et, Tavuk & Balık',  '€/kg',   true),
('pastirma',              'Pastırma',                 'marka', 'pastirma',                       'Et, Tavuk & Balık',  '€/kg',   true),
('salam-hindi-dana',      'Salam (Hindi/Dana)',        'sepet', 'salami',                        'Et, Tavuk & Balık',  '€/kg',   false),
('hindi-jambon',          'Hindi Jambon',             'sepet', 'kalkoenham',                     'Et, Tavuk & Balık',  '€/kg',   false),
('somon-fileto',          'Somon Fileto',             'sepet', 'zalmfilet',                      'Et, Tavuk & Balık',  '€/kg',   false),
('uskumru',               'Uskumru',                  'sepet', 'makreel',                        'Et, Tavuk & Balık',  '€/kg',   false),
('hamsi-sprat',           'Hamsi / Sprat',            'sepet', 'sprot ansjovis',                 'Et, Tavuk & Balık',  '€/kg',   false),
('levrek-cipura',         'Levrek / Çipura',          'sepet', 'zeebaars dorade',                'Et, Tavuk & Balık',  '€/kg',   false),
('karides',               'Karides',                  'sepet', 'garnalen',                       'Et, Tavuk & Balık',  '€/kg',   false),
('ton-baligi-konserve',   'Ton Balığı Konserve',      'marka', 'tonijn in blik',                 'Et, Tavuk & Balık',  '€/kg',   false),
('sardalya-konserve',     'Sardalya Konserve',        'sepet', 'sardines in blik',               'Et, Tavuk & Balık',  '€/kg',   false),

-- ─── 3. Sebze (30) ───────────────────────────────────────────
('domates',               'Domates',                  'sepet', 'tomaten 1kg',                    'Sebze',              '€/kg',   false),
('salkim-domates',        'Salkım Domates',           'sepet', 'trostomaten',                    'Sebze',              '€/kg',   false),
('salatalik',             'Salatalık',                'sepet', 'komkommer',                      'Sebze',              '€/adet', false),
('sari-sogan',            'Sarı Soğan',               'sepet', 'gele uien 1kg',                  'Sebze',              '€/kg',   false),
('kirmizi-sogan',         'Kırmızı Soğan',            'sepet', 'rode uien',                      'Sebze',              '€/kg',   false),
('sarimsak',              'Sarımsak',                 'sepet', 'knoflook',                       'Sebze',              '€/kg',   false),
('patates',               'Patates',                  'sepet', 'aardappelen kg',                 'Sebze',              '€/kg',   false),
('sivri-biber',           'Sivri Biber',              'sepet', 'spitse paprika',                 'Sebze',              '€/kg',   false),
('renkli-dolma-biber',    'Renkli Dolma Biber',       'sepet', 'paprika',                        'Sebze',              '€/kg',   false),
('patlican',              'Patlıcan',                 'sepet', 'aubergine',                      'Sebze',              '€/kg',   false),
('kabak',                 'Kabak',                    'sepet', 'courgette',                      'Sebze',              '€/kg',   false),
('havuc',                 'Havuç',                    'sepet', 'wortelen 1kg',                   'Sebze',              '€/kg',   false),
('marul',                 'Marul',                    'sepet', 'kropsla',                        'Sebze',              '€/adet', false),
('maydanoz',              'Maydanoz',                 'sepet', 'peterselie',                     'Sebze',              '€/adet', false),
('dereotu',               'Dereotu',                  'sepet', 'dille',                          'Sebze',              '€/adet', false),
('nane-taze',             'Nane',                     'sepet', 'munt',                           'Sebze',              '€/adet', false),
('taze-sogan',            'Taze Soğan',               'sepet', 'lente-ui',                       'Sebze',              '€/adet', false),
('pirasa',                'Pırasa',                   'sepet', 'prei',                           'Sebze',              '€/kg',   false),
('ispanak',               'Ispanak',                  'sepet', 'spinazie',                       'Sebze',              '€/kg',   false),
('brokoli',               'Brokoli',                  'sepet', 'broccoli',                       'Sebze',              '€/kg',   false),
('karnabahar',            'Karnabahar',               'sepet', 'bloemkool',                      'Sebze',              '€/adet', false),
('beyaz-lahana',          'Beyaz Lahana',             'sepet', 'witte kool',                     'Sebze',              '€/kg',   false),
('kirmizi-lahana',        'Kırmızı Lahana',           'sepet', 'rode kool',                      'Sebze',              '€/kg',   false),
('mantar',                'Mantar',                   'sepet', 'champignons',                    'Sebze',              '€/kg',   false),
('bamya',                 'Bamya',                    'sepet', 'okra',                           'Sebze',              '€/kg',   true),
('taze-fasulye',          'Taze Fasulye',             'sepet', 'prinsessenbonen',                'Sebze',              '€/kg',   false),
('bezelye-taze',          'Bezelye',                  'sepet', 'erwten',                         'Sebze',              '€/kg',   false),
('taze-misir',            'Taze Mısır',               'sepet', 'maïs',                           'Sebze',              '€/adet', false),
('turp',                  'Turp',                     'sepet', 'radijs',                         'Sebze',              '€/kg',   false),
('pancar',                'Pancar',                   'sepet', 'rode biet',                      'Sebze',              '€/kg',   false),

-- ─── 4. Meyve (22) ───────────────────────────────────────────
('muz',                   'Muz',                      'sepet', 'bananen 1kg',                    'Meyve',              '€/kg',   false),
('elma',                  'Elma',                     'sepet', 'appelen 1kg',                    'Meyve',              '€/kg',   false),
('armut',                 'Armut',                    'sepet', 'peren',                          'Meyve',              '€/kg',   false),
('portakal',              'Portakal',                 'sepet', 'sinaasappelen',                  'Meyve',              '€/kg',   false),
('mandalina',             'Mandalina',                'sepet', 'mandarijnen',                    'Meyve',              '€/kg',   false),
('limon',                 'Limon',                    'sepet', 'citroenen',                      'Meyve',              '€/kg',   false),
('uzum',                  'Üzüm',                     'sepet', 'druiven',                        'Meyve',              '€/kg',   false),
('cilek',                 'Çilek',                    'sepet', 'aardbeien',                      'Meyve',              '€/kg',   false),
('karpuz',                'Karpuz',                   'sepet', 'watermeloen',                    'Meyve',              '€/kg',   false),
('kavun',                 'Kavun',                    'sepet', 'meloen',                         'Meyve',              '€/kg',   false),
('seftali-nektarin',      'Şeftali / Nektarin',       'sepet', 'perzik nectarine',               'Meyve',              '€/kg',   false),
('kayisi',                'Kayısı',                   'sepet', 'abrikozen',                      'Meyve',              '€/kg',   false),
('erik',                  'Erik',                     'sepet', 'pruimen',                        'Meyve',              '€/kg',   false),
('kiraz',                 'Kiraz',                    'sepet', 'kersen',                         'Meyve',              '€/kg',   false),
('ananas',                'Ananas',                   'sepet', 'ananas',                         'Meyve',              '€/adet', false),
('kivi',                  'Kivi',                     'sepet', 'kiwi',                           'Meyve',              '€/kg',   false),
('nar',                   'Nar',                      'sepet', 'granaatappel',                   'Meyve',              '€/adet', false),
('avokado',               'Avokado',                  'sepet', 'avocado',                        'Meyve',              '€/adet', false),
('taze-incir',            'Taze İncir',               'sepet', 'vijgen',                         'Meyve',              '€/kg',   false),
('hurma',                 'Hurma',                    'sepet', 'dadels',                         'Meyve',              '€/kg',   false),
('kuru-uzum',             'Kuru Üzüm',                'sepet', 'rozijnen',                       'Meyve',              '€/kg',   false),
('kuru-kayisi',           'Kuru Kayısı',              'sepet', 'gedroogde abrikozen',            'Meyve',              '€/kg',   false),

-- ─── 5. Temel Kuru Gıda (25) ─────────────────────────────────
('pirinc-uzun-tane',      'Pirinç (Uzun Tane)',       'sepet', 'rijst 1kg',                      'Temel Kuru Gıda',    '€/kg',   false),
('pilavlik-pirinc',       'Pilavlık Pirinç',          'sepet', 'rondkorrelrijst',                'Temel Kuru Gıda',    '€/kg',   false),
('basmati-pirinc',        'Basmati Pirinç',           'sepet', 'basmatirijst',                   'Temel Kuru Gıda',    '€/kg',   false),
('pilavlik-bulgur',       'Pilavlık Bulgur',          'sepet', 'grove bulgur',                   'Temel Kuru Gıda',    '€/kg',   false),
('koftelik-ince-bulgur',  'Köftelik İnce Bulgur',     'sepet', 'fijne bulgur',                   'Temel Kuru Gıda',    '€/kg',   false),
('kuskus',                'Kuskus',                   'sepet', 'couscous',                       'Temel Kuru Gıda',    '€/kg',   false),
('spaghetti',             'Spaghetti',                'sepet', 'spaghetti 500g',                 'Temel Kuru Gıda',    '€/kg',   false),
('penne-fusilli',         'Penne / Fusilli',          'sepet', 'penne fusilli',                  'Temel Kuru Gıda',    '€/kg',   false),
('sehriye',               'Şehriye',                  'sepet', 'vermicelli',                     'Temel Kuru Gıda',    '€/kg',   false),
('eriste',                'Erişte',                   'sepet', 'eiernoedels',                    'Temel Kuru Gıda',    '€/kg',   false),
('cok-amacli-un',         'Çok Amaçlı Un',            'sepet', 'bloem 1kg',                      'Temel Kuru Gıda',    '€/kg',   false),
('tam-bugday-unu',        'Tam Buğday Unu',           'sepet', 'volkorenmeel',                   'Temel Kuru Gıda',    '€/kg',   false),
('irmik',                 'İrmik',                    'sepet', 'griesmeel',                      'Temel Kuru Gıda',    '€/kg',   false),
('nisasta',               'Nişasta',                  'sepet', 'maïzena',                        'Temel Kuru Gıda',    '€/kg',   false),
('toz-seker',             'Toz Şeker',                'sepet', 'suiker 1kg',                     'Temel Kuru Gıda',    '€/kg',   false),
('pudra-sekeri',          'Pudra Şekeri',             'sepet', 'bloemsuiker',                    'Temel Kuru Gıda',    '€/kg',   false),
('esmer-seker',           'Esmer Şeker',              'sepet', 'bruine suiker',                  'Temel Kuru Gıda',    '€/kg',   false),
('tuz',                   'Tuz',                      'sepet', 'zout 1kg',                       'Temel Kuru Gıda',    '€/kg',   false),
('kabartma-tozu',         'Kabartma Tozu',            'sepet', 'bakpoeder',                      'Temel Kuru Gıda',    '€/adet', false),
('instant-maya',          'İnstant Maya',             'sepet', 'gist',                           'Temel Kuru Gıda',    '€/adet', false),
('vanilya-vanilin',       'Vanilya / Vanilin',        'sepet', 'vanillesuiker',                  'Temel Kuru Gıda',    '€/adet', false),
('kakao',                 'Kakao',                    'sepet', 'cacaopoeder',                    'Temel Kuru Gıda',    '€/kg',   false),
('galeta-unu',            'Galeta Unu',               'sepet', 'paneermeel',                     'Temel Kuru Gıda',    '€/kg',   false),
('yulaf-ezmesi',          'Yulaf Ezmesi',             'sepet', 'havermout',                      'Temel Kuru Gıda',    '€/kg',   false),
('misir-nisastasi',       'Mısır Nişastası',          'sepet', 'bakingredients',                 'Temel Kuru Gıda',    '€/kg',   false),

-- ─── 6. Bakliyat & Konserve (15) ─────────────────────────────
('yesil-mercimek',        'Yeşil Mercimek',           'sepet', 'groene linzen',                  'Bakliyat & Konserve','€/kg',   false),
('kirmizi-mercimek',      'Kırmızı Mercimek',         'sepet', 'rode linzen',                    'Bakliyat & Konserve','€/kg',   false),
('kuru-nohut',            'Kuru Nohut',               'sepet', 'kikkererwten droog',             'Bakliyat & Konserve','€/kg',   false),
('nohut-konserve',        'Nohut Konserve',           'sepet', 'kikkererwten blik',              'Bakliyat & Konserve','€/kg',   false),
('kuru-fasulye',          'Kuru Fasulye',             'sepet', 'witte bonen droog',              'Bakliyat & Konserve','€/kg',   false),
('barbunya',              'Barbunya',                 'sepet', 'borlottibonen',                  'Bakliyat & Konserve','€/kg',   false),
('fasulye-konserve',      'Fasulye Konserve',         'sepet', 'bonen in blik',                  'Bakliyat & Konserve','€/kg',   false),
('dogranmis-domates-konserve', 'Doğranmış Domates Konserve', 'sepet', 'tomatenblokjes blik',    'Bakliyat & Konserve','€/kg',   false),
('domates-passata',       'Domates Passata',          'sepet', 'passata',                        'Bakliyat & Konserve','€/kg',   false),
('domates-salcasi',       'Domates Salçası',          'sepet', 'tomatenpuree',                   'Bakliyat & Konserve','€/kg',   false),
('biber-salcasi',         'Biber Salçası',            'marka', 'ajvar pepersaus',                'Bakliyat & Konserve','€/kg',   true),
('misir-konserve',        'Mısır Konserve',           'sepet', 'maïs blik',                      'Bakliyat & Konserve','€/kg',   false),
('bezelye-konserve',      'Bezelye Konserve',         'sepet', 'erwten blik',                    'Bakliyat & Konserve','€/kg',   false),
('yesil-zeytin',          'Yeşil Zeytin',             'sepet', 'groene olijven',                 'Bakliyat & Konserve','€/kg',   false),
('siyah-zeytin',          'Siyah Zeytin',             'sepet', 'zwarte olijven',                 'Bakliyat & Konserve','€/kg',   false),

-- ─── 7. Yağ, Sirke & Sos (15) ────────────────────────────────
('aycicek-yagi',          'Ayçiçek Yağı',             'sepet', 'zonnebloemolie 1L',              'Yağ, Sirke & Sos',   '€/L',    false),
('sizme-zeytinyagi',      'Sızma Zeytinyağı',         'sepet', 'olijfolie extra vierge 1L',      'Yağ, Sirke & Sos',   '€/L',    false),
('misirozu-yagi',         'Mısırözü Yağı',            'sepet', 'maïsolie',                       'Yağ, Sirke & Sos',   '€/L',    false),
('kizartma-yagi',         'Kızartma Yağı',            'sepet', 'frituurolie',                    'Yağ, Sirke & Sos',   '€/L',    false),
('elma-sirkesi',          'Beyaz / Elma Sirkesi',     'sepet', 'azijn appelazijn',               'Yağ, Sirke & Sos',   '€/L',    false),
('nar-eksi',              'Nar Ekşisi',               'marka', 'granaatappelsiroop',             'Yağ, Sirke & Sos',   '€/L',    true),
('limon-sosu',            'Limon Sosu',               'sepet', 'citroensap',                     'Yağ, Sirke & Sos',   '€/L',    false),
('mayonez',               'Mayonez',                  'marka', 'mayonaise',                      'Yağ, Sirke & Sos',   '€/kg',   false),
('ketchap',               'Ketçap',                   'marka', 'ketchup',                        'Yağ, Sirke & Sos',   '€/kg',   false),
('hardal',                'Hardal',                   'sepet', 'mosterd',                        'Yağ, Sirke & Sos',   '€/kg',   false),
('soya-sosu',             'Soya Sosu',                'marka', 'sojasaus',                       'Yağ, Sirke & Sos',   '€/L',    false),
('aci-sos',               'Acı Sos',                  'marka', 'hot sauce sambal',               'Yağ, Sirke & Sos',   '€/L',    false),
('salata-sosu',           'Salata Sosu',              'marka', 'dressing',                       'Yağ, Sirke & Sos',   '€/L',    false),
('tahin',                 'Tahin',                    'marka', 'tahin sesampasta',               'Yağ, Sirke & Sos',   '€/kg',   true),
('pesto-hazir-sos',       'Pesto / Hazır Sos',        'marka', 'pesto pastasaus',                'Yağ, Sirke & Sos',   '€/kg',   false),

-- ─── 8. Baharat & Çeşni (18) ─────────────────────────────────
('karabiber-toz',         'Karabiber',                'sepet', 'zwarte peper',                   'Baharat & Çeşni',    '€/kg',   false),
('toz-kirmizi-biber',     'Toz Kırmızı Biber',        'sepet', 'paprikapoeder',                  'Baharat & Çeşni',    '€/kg',   false),
('pul-biber',             'Pul Biber',                'sepet', 'chilivlokken',                   'Baharat & Çeşni',    '€/kg',   false),
('kimyon',                'Kimyon',                   'sepet', 'komijn',                         'Baharat & Çeşni',    '€/kg',   false),
('kekik',                 'Kekik',                    'sepet', 'oregano tijm',                   'Baharat & Çeşni',    '€/kg',   false),
('kuru-nane',             'Kuru Nane',                'sepet', 'gedroogde munt',                 'Baharat & Çeşni',    '€/kg',   false),
('tarcin',                'Tarçın',                   'sepet', 'kaneel',                         'Baharat & Çeşni',    '€/kg',   false),
('kori',                  'Köri',                     'sepet', 'kerrie',                         'Baharat & Çeşni',    '€/kg',   false),
('zerdeçal',              'Zerdeçal',                 'sepet', 'kurkuma',                        'Baharat & Çeşni',    '€/kg',   false),
('sumak',                 'Sumak',                    'marka', 'sumak',                          'Baharat & Çeşni',    '€/kg',   true),
('isot',                  'İsot',                     'marka', 'isot',                           'Baharat & Çeşni',    '€/kg',   true),
('kofte-tavuk-baharati',  'Köfte / Tavuk Baharatı',   'marka', 'kruidenmix',                     'Baharat & Çeşni',    '€/kg',   false),
('tane-karabiber',        'Tane Karabiber',           'sepet', 'peperkorrels',                   'Baharat & Çeşni',    '€/kg',   false),
('defne-yapragI',         'Defne Yaprağı',            'sepet', 'laurier',                        'Baharat & Çeşni',    '€/adet', false),
('bulyon-corba-bazi',     'Bulyon / Çorba Bazı',      'marka', 'bouillonblokjes',                'Baharat & Çeşni',    '€/adet', false),
('cesni-karisimi',        'Çeşni Karışımı (Vegeta)',  'marka', 'aromat',                         'Baharat & Çeşni',    '€/kg',   false),
('susam',                 'Susam',                    'sepet', 'sesamzaad',                      'Baharat & Çeşni',    '€/kg',   false),
('corek-otu',             'Çörek Otu',                'marka', 'nigella',                        'Baharat & Çeşni',    '€/kg',   true),

-- ─── 9. Ekmek & Unlu Mamul (15) ──────────────────────────────
('beyaz-ekmek',           'Beyaz Ekmek',              'sepet', 'wit brood 800g',                 'Ekmek & Unlu Mamul', '€/kg',   false),
('tam-bugday-ekmek',      'Tam Buğday Ekmek',         'sepet', 'volkorenbrood',                  'Ekmek & Unlu Mamul', '€/kg',   false),
('baget',                 'Baget',                    'sepet', 'stokbrood baguette',             'Ekmek & Unlu Mamul', '€/adet', false),
('pita-ekmegi',           'Pita Ekmeği',              'sepet', 'pitabrood',                      'Ekmek & Unlu Mamul', '€/adet', false),
('lavas-durum',           'Lavaş / Dürüm',            'sepet', 'wraps tortilla',                 'Ekmek & Unlu Mamul', '€/adet', false),
('tost-ekmegi',           'Tost Ekmeği',              'sepet', 'toastbrood',                     'Ekmek & Unlu Mamul', '€/kg',   false),
('kepekli-sandvic',       'Kepekli Sandviç Ekmeği',   'sepet', 'volkoren sandwiches',            'Ekmek & Unlu Mamul', '€/kg',   false),
('simit',                 'Simit',                    'marka', 'simit',                          'Ekmek & Unlu Mamul', '€/adet', true),
('yufka',                 'Yufka',                    'marka', 'filodeeg yufka',                 'Ekmek & Unlu Mamul', '€/kg',   true),
('milfoy-hamuru',         'Milföy Hamuru',            'sepet', 'bladerdeeg',                     'Ekmek & Unlu Mamul', '€/kg',   false),
('pizza-hamuru',          'Pizza Hamuru',             'sepet', 'pizzadeeg',                      'Ekmek & Unlu Mamul', '€/adet', false),
('kraker',                'Kraker',                   'sepet', 'crackers',                       'Ekmek & Unlu Mamul', '€/kg',   false),
('galeta-beschuit',       'Galeta (Beschuit)',         'sepet', 'beschuit',                       'Ekmek & Unlu Mamul', '€/kg',   false),
('kruvazan',              'Kruvasan',                 'sepet', 'croissant',                      'Ekmek & Unlu Mamul', '€/adet', false),
('kek-pasta-bazi',        'Kek / Pasta Bazı',         'marka', 'cakemix',                        'Ekmek & Unlu Mamul', '€/kg',   false),

-- ─── 10. Kahvaltılık (18) ────────────────────────────────────
('kahvaltilik-yesil-zeytin', 'Kahvaltılık Yeşil Zeytin', 'sepet', 'groene olijven',             'Kahvaltılık',        '€/kg',   false),
('kahvaltilik-siyah-zeytin', 'Kahvaltılık Siyah Zeytin', 'sepet', 'zwarte olijven',             'Kahvaltılık',        '€/kg',   false),
('suzme-bal',             'Süzme Bal',                'sepet', 'honing',                         'Kahvaltılık',        '€/kg',   false),
('petek-bal',             'Petek Bal',                'marka', 'raathoning',                     'Kahvaltılık',        '€/kg',   false),
('visne-cilek-receli',    'Vişne / Çilek Reçeli',     'sepet', 'confituur',                      'Kahvaltılık',        '€/kg',   false),
('nutella',               'Nutella',                  'marka', 'nutella',                        'Kahvaltılık',        '€/kg',   false),
('cikolatali-krema',      'Çikolatalı Krema',         'sepet', 'choco hazelnootpasta',           'Kahvaltılık',        '€/kg',   false),
('fistik-ezmesi',         'Fıstık Ezmesi',            'marka', 'pindakaas',                      'Kahvaltılık',        '€/kg',   false),
('kaymak',                'Kaymak (Sürülebilir)',     'marka', 'kaymak',                         'Kahvaltılık',        '€/kg',   true),
('kahvaltilik-beyaz-peynir', 'Kahvaltılık Beyaz Peynir', 'sepet', 'feta',                       'Kahvaltılık',        '€/kg',   false),
('kahvaltilik-sucuk',     'Kahvaltılık Sucuk',        'marka', 'sucuk helal',                    'Kahvaltılık',        '€/kg',   true),
('kahvaltilik-sosis',     'Kahvaltılık Sosis',        'sepet', 'ontbijtworst',                   'Kahvaltılık',        '€/kg',   false),
('misir-gevregi',         'Mısır Gevreği',            'marka', 'cornflakes',                     'Kahvaltılık',        '€/kg',   false),
('musli-granola',         'Müsli / Granola',          'sepet', 'muesli granola',                 'Kahvaltılık',        '€/kg',   false),
('cocuk-tahil-gevregi',   'Çocuk Tahıl Gevreği',      'marka', 'ontbijtgranen',                  'Kahvaltılık',        '€/kg',   false),
('tahin-pekmez',          'Tahin Pekmez',             'marka', 'tahin pekmez',                   'Kahvaltılık',        '€/kg',   true),
('krep-pankek-karisimi',  'Krep / Pankek Karışımı',   'marka', 'pannenkoekmix',                  'Kahvaltılık',        '€/kg',   false),
('yulaf-lapa',            'Yulaf / Lapa',             'sepet', 'havermout',                      'Kahvaltılık',        '€/kg',   false),

-- ─── 11. İçecek (25) ─────────────────────────────────────────
('poset-siyah-cay',       'Poşet Siyah Çay',          'marka', 'zwarte thee zakjes',             'İçecek',             '€/adet', false),
('dokme-siyah-cay',       'Dökme Siyah Çay',          'marka', 'losse thee',                     'İçecek',             '€/kg',   true),
('yesil-cay',             'Yeşil Çay',                'marka', 'groene thee',                    'İçecek',             '€/adet', false),
('bitki-cayi',            'Bitki Çayı (Ihlamur/Nane)', 'sepet', 'kruidenthee',                   'İçecek',             '€/adet', false),
('turk-kahvesi',          'Türk Kahvesi',             'marka', 'Turkse koffie',                  'İçecek',             '€/kg',   true),
('filtre-kahve',          'Filtre / Öğütülmüş Kahve', 'marka', 'gemalen koffie',                 'İçecek',             '€/kg',   false),
('cekirdek-kahve',        'Çekirdek Kahve',           'marka', 'koffiebonen',                    'İçecek',             '€/kg',   false),
('granul-kahve',          'Granül Kahve',             'marka', 'oploskoffie',                    'İçecek',             '€/kg',   false),
('coca-cola',             'Kola',                     'marka', 'Coca-Cola',                      'İçecek',             '€/L',    false),
('coca-cola-zero',        'Kola Zero / Light',        'marka', 'Coca-Cola Zero',                 'İçecek',             '€/L',    false),
('fanta-sprite',          'Fanta / Sprite',           'marka', 'Fanta Sprite',                   'İçecek',             '€/L',    false),
('gazoz-limonata',        'Gazoz / Limonata',         'sepet', 'limonade',                       'İçecek',             '€/L',    false),
('maden-suyu',            'Maden Suyu',               'sepet', 'bruiswater',                     'İçecek',             '€/L',    false),
('soda',                  'Sade Soda',                'sepet', 'spuitwater',                     'İçecek',             '€/L',    false),
('su-buyuk-pet',          'Su (Büyük Pet)',            'sepet', 'plat water',                     'İçecek',             '€/L',    false),
('portakal-suyu',         'Portakal Suyu',            'sepet', 'sinaasappelsap',                 'İçecek',             '€/L',    false),
('elma-suyu',             'Elma Suyu',                'sepet', 'appelsap',                       'İçecek',             '€/L',    false),
('visne-suyu',            'Vişne Suyu',               'sepet', 'kersensap',                      'İçecek',             '€/L',    false),
('karisik-meyve-suyu',    'Karışık Meyve Suyu',       'sepet', 'multivruchtensap',               'İçecek',             '€/L',    false),
('salgam-suyu',           'Şalgam Suyu',              'marka', 'salgam suyu',                    'İçecek',             '€/L',    true),
('buzlu-cay',             'Buzlu Çay',                'marka', 'ice tea',                        'İçecek',             '€/L',    false),
('enerji-icecegi',        'Enerji İçeceği',           'marka', 'Red Bull energydrink',           'İçecek',             '€/L',    false),
('alkolsuz-bira',         'Alkolsüz Bira',            'marka', 'alcoholvrij bier',               'İçecek',             '€/L',    false),
('meyve-surubu',          'Meyve Şurubu',             'sepet', 'siroop',                         'İçecek',             '€/L',    false),
('sicak-cikolata-tozu',   'Sıcak Çikolata Tozu',      'marka', 'warme chocolademelk',            'İçecek',             '€/kg',   false),

-- ─── 12. Atıştırmalık & Tatlı (20) ───────────────────────────
('sutlu-cikolata-tableti', 'Sütlü Çikolata Tableti',  'marka', 'melkchocolade',                  'Atıştırmalık & Tatlı','€/kg',  false),
('bitter-cikolata',       'Bitter Çikolata',          'marka', 'pure chocolade',                 'Atıştırmalık & Tatlı','€/kg',  false),
('gofret',                'Gofret',                   'marka', 'wafel',                          'Atıştırmalık & Tatlı','€/kg',  false),
('biskuvi',               'Bisküvi (Petit Beurre)',   'sepet', 'koekjes',                        'Atıştırmalık & Tatlı','€/kg',  false),
('tuzlu-kraker',          'Tuzlu Kraker',             'sepet', 'zoutjes',                        'Atıştırmalık & Tatlı','€/kg',  false),
('patates-cipsi',         'Patates Cipsi',            'marka', 'chips',                          'Atıştırmalık & Tatlı','€/kg',  false),
('misir-cipsi',           'Mısır Cipsi / Nacho',      'marka', 'tortillachips',                  'Atıştırmalık & Tatlı','€/kg',  false),
('karisik-kuruyemis',     'Karışık Kuruyemiş',        'sepet', 'gemengde noten',                 'Atıştırmalık & Tatlı','€/kg',  false),
('findik',                'Fındık',                   'sepet', 'hazelnoten',                     'Atıştırmalık & Tatlı','€/kg',  false),
('ceviz',                 'Ceviz',                    'sepet', 'walnoten',                       'Atıştırmalık & Tatlı','€/kg',  false),
('badem',                 'Badem',                    'sepet', 'amandelen',                      'Atıştırmalık & Tatlı','€/kg',  false),
('antep-fistigi',         'Antep Fıstığı',            'sepet', 'pistachenoten',                  'Atıştırmalık & Tatlı','€/kg',  false),
('ay-cekirdegi',          'Ay Çekirdeği',             'sepet', 'zonnebloempitten',               'Atıştırmalık & Tatlı','€/kg',  false),
('leblebi',               'Leblebi',                  'marka', 'leblebi',                        'Atıştırmalık & Tatlı','€/kg',  true),
('lokum',                 'Lokum',                    'marka', 'Turks fruit',                    'Atıştırmalık & Tatlı','€/kg',  true),
('helva',                 'Helva',                    'marka', 'halva',                          'Atıştırmalık & Tatlı','€/kg',  true),
('sakiz-sekerleme',       'Sakız / Şekerleme',        'marka', 'snoep kauwgom',                  'Atıştırmalık & Tatlı','€/kg',  false),
('hazir-kek-pasta',       'Hazır Kek / Pasta',        'marka', 'cake',                           'Atıştırmalık & Tatlı','€/kg',  false),
('sutlu-tatli-hazir',     'Sütlü Tatlı (Hazır)',      'sepet', 'dessert pudding',                'Atıştırmalık & Tatlı','€/kg',  false),
('biskuvili-pasta',       'Bisküvili Pasta',          'marka', 'koek-snack',                     'Atıştırmalık & Tatlı','€/kg',  false),

-- ─── 13. Dondurulmuş (12) ────────────────────────────────────
('donmus-pizza',          'Donmuş Pizza',             'marka', 'diepvriespizza',                 'Dondurulmuş',        '€/adet', false),
('donmus-patates-kizartmasi', 'Donmuş Patates Kızartması', 'sepet', 'diepvriesfrieten',         'Dondurulmuş',        '€/kg',   false),
('donmus-karisik-sebze',  'Donmuş Karışık Sebze',     'sepet', 'diepvriesgroenten',              'Dondurulmuş',        '€/kg',   false),
('donmus-bezelye',        'Donmuş Bezelye',           'sepet', 'diepvrieserwten',                'Dondurulmuş',        '€/kg',   false),
('donmus-ispanak',        'Donmuş Ispanak',           'sepet', 'diepvriesspinazie',              'Dondurulmuş',        '€/kg',   false),
('donmus-meyve',          'Donmuş Meyve',             'sepet', 'diepvriesfruit',                 'Dondurulmuş',        '€/kg',   false),
('balik-cubugu',          'Balık Çubuğu',             'marka', 'vissticks',                      'Dondurulmuş',        '€/kg',   false),
('donmus-karides',        'Donmuş Karides',           'sepet', 'diepvriesgarnalen',              'Dondurulmuş',        '€/kg',   false),
('donmus-borek-yufka',    'Donmuş Börek / Yufka',     'marka', 'diepvries borek',                'Dondurulmuş',        '€/kg',   true),
('donmus-kofte',          'Donmuş Köfte',             'sepet', 'diepvriesballetjes',             'Dondurulmuş',        '€/kg',   false),
('dondurma-kutu',         'Dondurma (Kutu)',          'marka', 'roomijs',                        'Dondurulmuş',        '€/L',    false),
('tavuk-nugget-donmus',   'Tavuk Nugget (Donmuş)',    'marka', 'kipnuggets',                     'Dondurulmuş',        '€/kg',   false),

-- ─── 14. Bebek & Çocuk (8) ───────────────────────────────────
('bebek-bezi',            'Bebek Bezi',               'marka', 'luiers Pampers',                 'Bebek & Çocuk',      '€/adet', false),
('islak-mendil',          'Islak Mendil',             'sepet', 'babydoekjes',                    'Bebek & Çocuk',      '€/adet', false),
('kavanoz-mama',          'Kavanoz Mama',             'marka', 'babyvoeding potje',              'Bebek & Çocuk',      '€/adet', false),
('devam-sutu',            'Devam Sütü',               'marka', 'opvolgmelk',                     'Bebek & Çocuk',      '€/kg',   false),
('bebek-biskuvisi',       'Bebek Bisküvisi',          'marka', 'babykoekjes',                    'Bebek & Çocuk',      '€/kg',   false),
('tahil-mamasi',          'Tahıl Maması',             'marka', 'babypap',                        'Bebek & Çocuk',      '€/kg',   false),
('meyve-puresi',          'Meyve Püresi',             'sepet', 'fruithapje',                     'Bebek & Çocuk',      '€/adet', false),
('cocuk-icecek-kutusu',   'Çocuk İçecek Kutusu',     'marka', 'drinkpakje',                     'Bebek & Çocuk',      '€/L',    false),

-- ─── 15. Temizlik (15) ───────────────────────────────────────
('elde-bulasik-deterjani', 'Elde Bulaşık Deterjanı',  'sepet', 'afwasmiddel',                    'Temizlik',           '€/L',    false),
('bulasik-makinesi-tableti', 'Bulaşık Makinesi Tableti', 'marka', 'vaatwastabletten',            'Temizlik',           '€/adet', false),
('sivi-camasir-deterjani', 'Sıvı Çamaşır Deterjanı',  'marka', 'wasmiddel vloeibaar',            'Temizlik',           '€/yıkama',false),
('toz-camasir-deterjani', 'Toz Çamaşır Deterjanı',   'marka', 'waspoeder',                      'Temizlik',           '€/yıkama',false),
('camasir-yumusaticisi',  'Çamaşır Yumuşatıcısı',     'marka', 'wasverzachter',                  'Temizlik',           '€/L',    false),
('camasir-suyu',          'Çamaşır Suyu (Javel)',     'sepet', 'bleekwater javel',               'Temizlik',           '€/L',    false),
('yuzey-temizleyici',     'Yüzey Temizleyici',        'sepet', 'allesreiniger',                  'Temizlik',           '€/L',    false),
('cam-temizleyici',       'Cam Temizleyici',          'sepet', 'glasreiniger',                   'Temizlik',           '€/L',    false),
('banyo-temizleyici',     'Banyo Temizleyici',        'sepet', 'badkamerreiniger',               'Temizlik',           '€/L',    false),
('wc-jeli',               'WC Jeli',                  'sepet', 'wc-reiniger',                    'Temizlik',           '€/L',    false),
('bulasik-sungeri',       'Bulaşık Süngeri',          'sepet', 'schuurspons',                    'Temizlik',           '€/adet', false),
('cop-poseti',            'Çöp Poşeti',               'sepet', 'vuilniszakken',                  'Temizlik',           '€/adet', false),
('kirec-cozucu',          'Kireç Çözücü',             'sepet', 'ontkalker',                      'Temizlik',           '€/L',    false),
('el-sivi-sabunu',        'El Sıvı Sabunu',           'sepet', 'handzeep',                       'Temizlik',           '€/L',    false),
('dezenfektan',           'Dezenfektan',              'sepet', 'ontsmettingsmiddel',             'Temizlik',           '€/L',    false),

-- ─── 16. Kişisel Bakım & Kağıt (12) ──────────────────────────
('sampuan',               'Şampuan',                  'marka', 'shampoo',                        'Kişisel Bakım & Kağıt','€/L',  false),
('sac-kremi',             'Saç Kremi',                'marka', 'conditioner',                    'Kişisel Bakım & Kağıt','€/L',  false),
('dus-jeli',              'Duş Jeli',                 'marka', 'douchegel',                      'Kişisel Bakım & Kağıt','€/L',  false),
('kalip-sabun',           'Kalıp Sabun',              'sepet', 'zeep',                           'Kişisel Bakım & Kağıt','€/adet',false),
('dis-macunu',            'Diş Macunu',               'marka', 'tandpasta',                      'Kişisel Bakım & Kağıt','€/adet',false),
('dis-fircasi',           'Diş Fırçası',              'marka', 'tandenborstel',                  'Kişisel Bakım & Kağıt','€/adet',false),
('deodorant',             'Deodorant',                'marka', 'deodorant',                      'Kişisel Bakım & Kağıt','€/adet',false),
('tiras-kopugu',          'Tıraş Köpüğü',             'marka', 'scheerschuim',                   'Kişisel Bakım & Kağıt','€/adet',false),
('tuvalet-kagidi',        'Tuvalet Kağıdı',           'sepet', 'toiletpapier',                   'Kişisel Bakım & Kağıt','€/adet',false),
('kagit-havlu',           'Kağıt Havlu',              'sepet', 'keukenrol',                      'Kişisel Bakım & Kağıt','€/adet',false),
('kagit-mendil',          'Kağıt Mendil',             'sepet', 'zakdoeken',                      'Kişisel Bakım & Kağıt','€/adet',false),
('hijyenik-ped',          'Hijyenik Ped',             'marka', 'maandverband',                   'Kişisel Bakım & Kağıt','€/adet',false)

ON CONFLICT (slug) DO NOTHING;

-- Doğrulama sorgusu:
-- SELECT category, COUNT(*) FROM canonical_products GROUP BY category ORDER BY category;
